### ISSUE TITLE
Provide ClientAddr to application context unconditionally

### ISSUE THREAD

**Issue by nrempel** [djc/mendes#62]
Right now, `remote_addr` is collected and [provided to the application context](https://github.com/djc/mendes/blob/f505ea077186a096580e5e220f8e84c648f95d93/mendes/src/hyper.rs#L85) via hyper's [Extensions](https://docs.rs/http/0.2.8/http/struct.Extensions.html) utility. When retrieving the client ip, the application is left with an `Option<ClientAddr>`. However, it is possible for mendes to guarantee the existence of ClientAddr by embedding it directly in `Context`.

Would you consider adding something like `Context::client_addr` or `ClientAddr::extras` which includes that value?

I can make a pull request for that feature if you're open to it.

**Comment by djc** [comment]
The `Context` isn't really directly accessible to handers, right, because usually the handler would have destructed the `Context` already. However, providing a `FromContext` impl for `ClientAddr` seems like a reasonable alternative, what do you think?

**Comment by nrempel** [comment]
Oh yeah, I missed that.

Since `FromContext` is fallible, it doesn't change much. And, if I understand correctly, we'd still need to pull it out of `Extensions` and simply provide a different API to access `ClientAddr`.

In either case, this should be a safe `unwrap`. Adding the `FromContext` impl is a nicer API I think and may make that clearer to the user.

On the topic of `FromContext`: it looks like most impls return an `Ok(infallible_thing)`. Would it be reasonable to introduce a new infallible sibling of `from_context`? This might allow `Application` impls to unwrap less?
